require File.expand_path("lib/media")
require File.expand_path("lib/dvd")
require File.expand_path("lib/cd")
require File.expand_path("lib/book")
require File.expand_path("lib/library")
require File.expand_path("lib/report")
require File.expand_path("lib/database_files")
